name: PHP Lint & Codeception
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.2' ]
        experimental: [false]
        include:
          - php: '7.3'
            experimental: true
          - php: '7.4'
            experimental: true
          - php: '8.0'
            experimental: true
        
    
    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x

    - name: PHP Lint
      continue-on-error: true
      run: if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
    
    - name: Install NPM Dependency
      run: npm install -g grunt-cli && npm install
    
    - name: Grunt lint
      run: grunt lint --force
    
    - name: Grunt minify
      run: grunt minify
